### ISSUE TITLE
Bios Config

### ISSUE THREAD

**Issue by MichaelBundi333** [elmaleek03/HP-Elitebook-x360-1030-G4-Hackintosh#2]
Would you kindly share the bios configuration? I am having a hard time installing on my computer thank you.

**Comment by ITSYKV** [comment]
Hey, am facing some problem while installing the hackintosh too, it boots to the USB but then reboots to windows even after disabling the main m.2.

**Comment by elmaleek03** [comment]
> Would you kindly share the bios configuration? I am having a hard time installing on my computer thank you.

i forgot the bios settings, sorry for the inconvinience. i dont have the laptop anymore so i cant maintain update for this repo. for bios settings, you can refer to other repository of elitebook laptops with similar specs in github or other forum

**Comment by elmaleek03** [comment]
> Hey, am facing some problem while installing the hackintosh too, it boots to the USB but then reboots to windows even after disabling the main m.2.

so you finished the installer step and got stuck in the second phase? enable -v boot-args and post it here, maybe i can help with your problem

**Comment by ITSYKV** [comment]
https://github.com/user-attachments/assets/81b05700-92e7-499b-a3bf-436fdb2b07cb

**Comment by elmaleek03** [comment]
> https://github.com/user-attachments/assets/81b05700-92e7-499b-a3bf-436fdb2b07cb

navigate and select the install macos using your keyboard my guy 🗣️

**Comment by ITSYKV** [comment]
> > https://github.com/user-attachments/assets/81b05700-92e7-499b-a3bf-436fdb2b07cb
> 
> navigate and select the install macos using your keyboard my guy 🗣️

I enable what you told me to ( am new to this and I don't know much about it) ![image](https://github.com/user-attachments/assets/814bd790-3547-451a-b2b8-b117d99840d2) and now it's stuck on this

**Comment by elmaleek03** [comment]
@ITSYKV create a new issue thread and give your exact model laptop and its full specs.

you got IOG Flags 0x3 seems kind of different iGPU configuration with mine. thanks

**Comment by ITSYKV** [comment]
> @ITSYKV create a new issue thread and give your exact model laptop and its full specs.
> 
> you got IOG Flags 0x3 seems kind of different iGPU configuration with mine. thanks

Hey, I did create it can you please let me know if it's there or no because I never used GitHub
